### ISSUE TITLE
Fourier period

### ISSUE THREAD

**Issue by manso92** [GAA-UAM/fda#13]
I find on the original fda R code that the period of Fourier Basis is diff(domain_range) by default but we set it to 1 by default. Is it an issue or a improvement?

**Comment by vnmabus** [comment]
It is a bug. We should use the same default as R.

**Comment by manso92** [comment]
Perfect, I'll change it on apillar request

**Comment by vnmabus** [comment]
I think this is fixed in PR #24 so I will close the issue
