### ISSUE TITLE
FData class

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/fda#21]
In the branch `feature/fdata` I created the class `FData` to unify the API of `FDataBasis` and `FDataGrid`. It is just a suggestion of a possible API. I would like to discuss which methods are more appropriated to be in the common class and the interface of the methods.

In particular the api of `evaluate` and the parameter `keepdims`. 

https://github.com/GAA-UAM/fda/blob/859bb4055bd9a325fb1321ddb6b4d761013489ad/fda/fdata.py#L47-L50

**Comment by vnmabus** [comment]
First, remove the constructor, as FData is an abstract class.
Second, I think the properties should be abstract.

I think I agree with the other proposed changes.

**Comment by pablomm** [comment]
Closed in #26.
