### ISSUE TITLE
Plot function on Basis

### ISSUE THREAD

**Issue by manso92** [GAA-UAM/fda#33]
In this functions if checks for ndim_domain and ndim_image but this are attributes from FData object, not Basis objects

https://github.com/GAA-UAM/fda/blob/92c984cb42a505661716c26f4cd56a2f1e69e26f/fda/basis.py#L138-L155

**Comment by vnmabus** [comment]
I think this is a copy-paste bug. It would be better to call `to_basis().plot()` in my opinion, delegating all the work to the FDataBasis object.

**Comment by pablomm** [comment]
I probably thought it was the FDataBasis plot when I was _copy-pasting_. Will you fix it or me, @manso92?

**Comment by manso92** [comment]
Ill fix it don't worry
