### ISSUE TITLE
Numpy Future Warning

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/fda#46]
Since numpy 1.16 a warning is raised in basis.py:

> /home/travis/build/GAA-UAM/fda/fda/basis.py:917:
> FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support 
> for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an
> error in the future.
> self.knots[:-1]))

**Comment by manso92** [comment]
I've seen this warning too. I've look for uses in the code and we have some of this uses on it.

Are we going to change it now? Will we wait until it becomes and error?

**Comment by pablomm** [comment]
I didn't change it because I was working in other modules and it is not urgent, but I think that should be fixed.  After finishing the part I'm doing, I can fix it.
