### ISSUE TITLE
Add matplotlib as a dependency

### ISSUE THREAD

**Issue by vnmabus** [GAA-UAM/fda#47]
Matplotlib is currently imported, but it is not marked as a dependency in `setup.py`

**Comment by manso92** [comment]
But if a user wants to use the library without printing anything will we force it to install matplotlib?

**Comment by vnmabus** [comment]
In that case we should import matplotlib only inside the plotting functions. It could be done, but I do not think that is very important. Most of the users will want to plot, or they will have matplotlib in the default install and will not care.

**Comment by manso92** [comment]
Ok, if no one has anything against it, i'll fix it this weekend

**Comment by manso92** [comment]
I've open a [https://github.com/GAA-UAM/fda/pull/50](pull request) with it so I'll close the issue

https://github.com/GAA-UAM/fda/pull/50
