### ISSUE TITLE
Random seed in tests

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/fda#77]
The random state of the tests of magnitude shape plot is not being fixed, which makes the tests fail.

https://github.com/GAA-UAM/fda/blob/28a6e0b58053c29dd4fca0624d85ee44e00bbf19/fda/magnitude_shape_plot.py#L378

In the example of surface boxplot the random seed isn't being fixed either to generate the datasets.

**Comment by vnmabus** [comment]
Thank you for finding the bug, Pablo!

@amandaher, you should expose a random seed if there is randomness in a function. All seeds must be fixed in tests/examples to have reproducibility. You can look at the dataset generation utilities to see an example.

**Comment by vnmabus** [comment]
In fact, in this case, if the randomness come from the covariance estimation, I would say that the least surprising behaviour is to have a fixed seed by default, but allow changing it. What do you think?
